# Generated by Django 4.0.3 on 2022-03-25 13:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_no', models.CharField(max_length=6, verbose_name='Plate no')),
                ('vin_code', models.CharField(max_length=17, verbose_name='VIN code')),
                ('car_description', tinymce.models.HTMLField(help_text='Short car description', max_length=10000, verbose_name='Car description')),
                ('picture', models.ImageField(default='autoservice/img/default.png', upload_to='', verbose_name='Picture')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
                'ordering': ['plate_no'],
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='ex.: Audi, BMW, FIAT...', max_length=30, verbose_name='Brand')),
                ('model', models.CharField(max_length=30, verbose_name='Model')),
            ],
            options={
                'verbose_name': 'Car Model',
                'verbose_name_plural': 'Cars Models',
                'ordering': ['brand'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Price')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RepairOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('sum', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Sum')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('due_back', models.DateField(blank=True, db_index=True, default=datetime.date(2022, 4, 1), null=True, verbose_name='Due back')),
                ('status', models.PositiveIntegerField(choices=[(0, 'New'), (10, 'Accepted'), (20, 'Under repair'), (30, 'Done'), (50, 'Returned')], default=0, verbose_name='Status')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='autoservice.car', verbose_name='Car')),
            ],
            options={
                'verbose_name': 'Repair order',
                'verbose_name_plural': 'Repair orders',
                'ordering': ['due_back'],
            },
        ),
        migrations.CreateModel(
            name='OrderNo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Price')),
                ('remont_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_no', to='autoservice.repairorder', verbose_name='Remont Order')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='autoservice.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Repair job',
                'verbose_name_plural': 'Repair jobs',
                'ordering': ['remont_order'],
            },
        ),
        migrations.AddField(
            model_name='car',
            name='car_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='autoservice.carmodel', verbose_name='Car model'),
        ),
        migrations.AddField(
            model_name='car',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.userprofile', verbose_name='Client'),
        ),
    ]
