# Generated by Django 4.0.3 on 2022-03-25 13:46

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_description',
            field=tinymce.models.HTMLField(blank=True, default='', help_text='Short car description', max_length=10000, verbose_name='Car description'),
        ),
    ]
