# Generated by Django 4.0.3 on 2022-03-26 17:02

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0003_alter_repairorder_due_back'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('text', tinymce.models.HTMLField(blank=True, default='', max_length=10000, verbose_name='Comment')),
                ('for_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autoservice.repairorder')),
            ],
        ),
    ]
